echo -e "         ____"
echo -e "        /    \\"
echo -e "       / \e[31m稳定\e[0m \\"
echo -e "      /        \\"
echo -e "     +----------+"
echo -e "    /\\ \e[93m贵\e[0m /\\ \e[35m慢\e[0m /\\"
echo -e "   /  \\  /  \\  /  \\"
echo -e "  /    \\/____\\/    \\"
echo -e "  \\ \e[33m速度\e[0m\\ \e[32m差\e[0m / \e[34m便宜\e[0m/"
echo -e "   \\     \\  /     /"
echo -e "    \\_____\\/_____/"
echo
echo "推荐使用 三色图中央 的 VPS (不是"
echo "https://my.racknerd.com/aff.php?aff=1374&pid=924"
echo
echo "这个才是 三色图中央 的 VPN (才怪"
echo "https://justmysocks.net/members/aff.php?aff=256&gid=1"
echo
echo "现在下载sing-box 的压缩包"
echo "https://github.com/SagerNet/sing-box/releases/download/v1.12.15/sing-box-1.12.15-windows-amd64.zip"
wget "https://github.com/SagerNet/sing-box/releases/download/v1.12.15/sing-box-1.12.15-windows-amd64.zip"
